// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQdPEOpJcufL2ox1T97b-O0HLomG4AzRc',
    appId: '1:281181573124:web:c1c10af0b1eb728b6c6551',
    messagingSenderId: '281181573124',
    projectId: 'chatapp-f5eb6',
    authDomain: 'chatapp-f5eb6.firebaseapp.com',
    storageBucket: 'chatapp-f5eb6.appspot.com',
    measurementId: 'G-9036S3EE2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuDnBXdqsvTHBK3siUBsYcokxn0HYlfZY',
    appId: '1:281181573124:android:280fd2c50edbbba66c6551',
    messagingSenderId: '281181573124',
    projectId: 'chatapp-f5eb6',
    storageBucket: 'chatapp-f5eb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2HSFxwwSV_L3WG9LpVRSxh7mYKO5aODo',
    appId: '1:281181573124:ios:e321c9942e8e79906c6551',
    messagingSenderId: '281181573124',
    projectId: 'chatapp-f5eb6',
    storageBucket: 'chatapp-f5eb6.appspot.com',
    iosClientId: '281181573124-oa1sas83hp9hm8evq16sn6atf3jkk2f4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2HSFxwwSV_L3WG9LpVRSxh7mYKO5aODo',
    appId: '1:281181573124:ios:e321c9942e8e79906c6551',
    messagingSenderId: '281181573124',
    projectId: 'chatapp-f5eb6',
    storageBucket: 'chatapp-f5eb6.appspot.com',
    iosClientId: '281181573124-oa1sas83hp9hm8evq16sn6atf3jkk2f4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
